[package]
name = "nkdhr-canvas"
description = "The compositor and integrated shell runtime implementing the infinite pannable, zoomable canvas"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
default = ["nested"]
nested = ["smithay/backend_winit"]
tty = [
    "dep:smithay-drm-extras",
    "dep:thiserror",
    "smithay/backend_gbm",
    "smithay/backend_libinput",
    "smithay/backend_session_libseat",
    "smithay/backend_udev",
    "smithay/renderer_gl",
    "smithay/renderer_multi",
]

[dependencies]
nkdhr-ipc = { version = "0.1.0", path = "../nkdhr-ipc" }
nkdhr-render = { version = "0.1.0", path = "../nkdhr-render" }
nkdhr-settings = { version = "0.1.0", path = "../nkdhr-settings" }
nkdhr-ui = { version = "0.1.0", path = "../nkdhr-ui" }
smithay = { version = "0.7.0", default-features = false, features = ["desktop", "wayland_frontend", "xwayland"] }
smithay-drm-extras = { version = "0.1.0", default-features = false, optional = true }
thiserror = { version = "2.0.17", optional = true }
zbus = "5.18.0"
